"""
Django settings for misitio project.

Generated by 'django-admin startproject' using Django 1.8.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#contraseña asignada a nuestra base de datos
SECRET_KEY = 'udrsw($yj$2o!+wx^2p+e%u!9g0t@e@li*ct15f6-!4+n(hehh'

# SECURITY WARNING: don't run with debug turned on in production!
#mientras estamos programndo true, cunaod lo publicamos false
DEBUG = True
#quienes tiene permisos de entrar direcciones ip
ALLOWED_HOSTS = []


# Application definition
#que modulos trae instaldas por defectos
INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',#multimedia
    'django.contrib.sessions',#sesiones cuanto tiempo va a estar
    'django.contrib.messages',
    'django.contrib.staticfiles',#maneja iconos logotips}
    'blog',
)
#librerias
MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)
#cual es la pagina principal q va a cargar
ROOT_URLCONF = 'misitio.urls'
#donde tenemos nuestras plantillas web
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
#aplicacion q ejecuta los comandos
WSGI_APPLICATION = 'misitio.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases
#que base de datos usamos
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/
#idiomas
LANGUAGE_CODE = 'es-gt'#español

TIME_ZONE = 'America/Guatemala'#hora

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/
#donde van a estar los archivos estaticos
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
